# Base configs
#baseurl: "https://amoghvs.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Amogh Sondur"
subtitle: "See the world through my eyes!"
author: "Amogh Sondur"
header:
 title: "Photography"
 subtitle: "by Amogh Sondur"
