# Base configs
#baseurl: "https://amoghvs.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Amogh Sondur"
subtitle: "See the world through my eyes!"
author: "Amogh Sondur"
header:
 title: "Photography"
 subtitle: "by Amogh Sondur"
footer:
social_urls:
  #facebook: "https://www.facebook.com/amogh.v.s"
  #twitter: "https://www.twitter.com/amoghvs"
  #instagram: "https://www.instagram.com/amogh_sondur"
  linkedin: "https://in.linkedin.com/in/amoghsondur"
  github: "https://www.github.com/amoghvs"
  mail: "mailto:amoghvs@gmail.com"
